import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf.mjs';
import { createCanvas } from '@napi-rs/canvas';
import fs from 'fs';
import path from 'path';

// Standard 114 Surahs metadata
const SURAHS = [
  { "number": 1, "name": "Al-Fatihah", "arabicName": "الفاتحة", "meaning": "The Opening", "versesCount": 7, "revelationType": "Meccan", "juzStart": 1 },
  { "number": 2, "name": "Al-Baqarah", "arabicName": "البقرة", "meaning": "The Cow", "versesCount": 286, "revelationType": "Medinan", "juzStart": 1 },
  { "number": 3, "name": "Ali 'Imran", "arabicName": "آل عمران", "meaning": "Family of Imran", "versesCount": 200, "revelationType": "Medinan", "juzStart": 3 },
  { "number": 4, "name": "An-Nisa", "arabicName": "النساء", "meaning": "The Women", "versesCount": 176, "revelationType": "Medinan", "juzStart": 4 },
  { "number": 5, "name": "Al-Ma'idah", "arabicName": "المائدة", "meaning": "The Table Spread", "versesCount": 120, "revelationType": "Medinan", "juzStart": 6 },
  { "number": 6, "name": "Al-An'am", "arabicName": "الأنعام", "meaning": "The Cattle", "versesCount": 165, "revelationType": "Meccan", "juzStart": 7 },
  { "number": 7, "name": "Al-A'raf", "arabicName": "الأعراف", "meaning": "The Heights", "versesCount": 206, "revelationType": "Meccan", "juzStart": 8 },
  { "number": 8, "name": "Al-Anfal", "arabicName": "الأنفال", "meaning": "The Spoils of War", "versesCount": 75, "revelationType": "Medinan", "juzStart": 9 },
  { "number": 9, "name": "At-Tawbah", "arabicName": "التوبة", "meaning": "The Repentance", "versesCount": 129, "revelationType": "Medinan", "juzStart": 10 },
  { "number": 10, "name": "Yunus", "arabicName": "يونس", "meaning": "Jonah", "versesCount": 109, "revelationType": "Meccan", "juzStart": 11 },
  { "number": 11, "name": "Hud", "arabicName": "هود", "meaning": "Hud", "versesCount": 123, "revelationType": "Meccan", "juzStart": 11 },
  { "number": 12, "name": "Yusuf", "arabicName": "يوسف", "meaning": "Joseph", "versesCount": 111, "revelationType": "Meccan", "juzStart": 12 },
  { "number": 13, "name": "Ar-Ra'd", "arabicName": "الرعد", "meaning": "The Thunder", "versesCount": 43, "revelationType": "Medinan", "juzStart": 13 },
  { "number": 14, "name": "Ibrahim", "arabicName": "إبراهيم", "meaning": "Abraham", "versesCount": 52, "revelationType": "Meccan", "juzStart": 13 },
  { "number": 15, "name": "Al-Hijr", "arabicName": "الحجر", "meaning": "The Rocky Tract", "versesCount": 99, "revelationType": "Meccan", "juzStart": 14 },
  { "number": 16, "name": "An-Nahl", "arabicName": "النحل", "meaning": "The Bee", "versesCount": 128, "revelationType": "Meccan", "juzStart": 14 },
  { "number": 17, "name": "Al-Isra", "arabicName": "الإسراء", "meaning": "The Night Journey", "versesCount": 111, "revelationType": "Meccan", "juzStart": 15 },
  { "number": 18, "name": "Al-Kahf", "arabicName": "الكهف", "meaning": "The Cave", "versesCount": 110, "revelationType": "Meccan", "juzStart": 15 },
  { "number": 19, "name": "Maryam", "arabicName": "مريم", "meaning": "Mary", "versesCount": 98, "revelationType": "Meccan", "juzStart": 16 },
  { "number": 20, "name": "Taha", "arabicName": "طه", "meaning": "Ta-Ha", "versesCount": 135, "revelationType": "Meccan", "juzStart": 16 },
  { "number": 21, "name": "Al-Anbiya", "arabicName": "الأنبياء", "meaning": "The Prophets", "versesCount": 112, "revelationType": "Meccan", "juzStart": 17 },
  { "number": 22, "name": "Al-Hajj", "arabicName": "الحج", "meaning": "The Pilgrimage", "versesCount": 78, "revelationType": "Medinan", "juzStart": 17 },
  { "number": 23, "name": "Al-Mu'minun", "arabicName": "المؤمنون", "meaning": "The Believers", "versesCount": 118, "revelationType": "Meccan", "juzStart": 18 },
  { "number": 24, "name": "An-Nur", "arabicName": "النور", "meaning": "The Light", "versesCount": 64, "revelationType": "Medinan", "juzStart": 18 },
  { "number": 25, "name": "Al-Furqan", "arabicName": "الفرقان", "meaning": "The Criterion", "versesCount": 77, "revelationType": "Meccan", "juzStart": 18 },
  { "number": 26, "name": "Ash-Shu'ara", "arabicName": "الشعراء", "meaning": "The Poets", "versesCount": 227, "revelationType": "Meccan", "juzStart": 19 },
  { "number": 27, "name": "An-Naml", "arabicName": "النمل", "meaning": "The Ant", "versesCount": 93, "revelationType": "Meccan", "juzStart": 19 },
  { "number": 28, "name": "Al-Qasas", "arabicName": "القصص", "meaning": "The Stories", "versesCount": 88, "revelationType": "Meccan", "juzStart": 20 },
  { "number": 29, "name": "Al-'Ankabut", "arabicName": "العنكبوت", "meaning": "The Spider", "versesCount": 69, "revelationType": "Meccan", "juzStart": 20 },
  { "number": 30, "name": "Ar-Rum", "arabicName": "الروم", "meaning": "The Romans", "versesCount": 60, "revelationType": "Meccan", "juzStart": 21 },
  { "number": 31, "name": "Luqman", "arabicName": "لقمان", "meaning": "Luqman", "versesCount": 34, "revelationType": "Meccan", "juzStart": 21 },
  { "number": 32, "name": "As-Sajdah", "arabicName": "السجدة", "meaning": "The Prostration", "versesCount": 30, "revelationType": "Meccan", "juzStart": 21 },
  { "number": 33, "name": "Al-Ahzab", "arabicName": "الأحزاب", "meaning": "The Combined Forces", "versesCount": 73, "revelationType": "Medinan", "juzStart": 21 },
  { "number": 34, "name": "Saba", "arabicName": "سبأ", "meaning": "Sheba", "versesCount": 54, "revelationType": "Meccan", "juzStart": 22 },
  { "number": 35, "name": "Fatir", "arabicName": "فاطر", "meaning": "The Originator", "versesCount": 45, "revelationType": "Meccan", "juzStart": 22 },
  { "number": 36, "name": "Ya-Sin", "arabicName": "يس", "meaning": "Ya-Sin", "versesCount": 83, "revelationType": "Meccan", "juzStart": 22 },
  { "number": 37, "name": "As-Saffat", "arabicName": "الصافات", "meaning": "Those Who Set The Ranks", "versesCount": 182, "revelationType": "Meccan", "juzStart": 23 },
  { "number": 38, "name": "Sad", "arabicName": "ص", "meaning": "Sad", "versesCount": 88, "revelationType": "Meccan", "juzStart": 23 },
  { "number": 39, "name": "Az-Zumar", "arabicName": "الزمر", "meaning": "The Troops", "versesCount": 75, "revelationType": "Meccan", "juzStart": 23 },
  { "number": 40, "name": "Ghafir", "arabicName": "غافر", "meaning": "The Forgiver", "versesCount": 85, "revelationType": "Meccan", "juzStart": 24 },
  { "number": 41, "name": "Fussilat", "arabicName": "فصلت", "meaning": "Explained in Detail", "versesCount": 54, "revelationType": "Meccan", "juzStart": 24 },
  { "number": 42, "name": "Ash-Shura", "arabicName": "الشورى", "meaning": "The Consultation", "versesCount": 53, "revelationType": "Meccan", "juzStart": 25 },
  { "number": 43, "name": "Az-Zukhruf", "arabicName": "الزخرف", "meaning": "The Ornaments of Gold", "versesCount": 89, "revelationType": "Meccan", "juzStart": 25 },
  { "number": 44, "name": "Ad-Dukhan", "arabicName": "الدخان", "meaning": "The Smoke", "versesCount": 59, "revelationType": "Meccan", "juzStart": 25 },
  { "number": 45, "name": "Al-Jathiyah", "arabicName": "الجاثية", "meaning": "The Crouching", "versesCount": 37, "revelationType": "Meccan", "juzStart": 25 },
  { "number": 46, "name": "Al-Ahqaf", "arabicName": "الأحقاف", "meaning": "The Wind-Curved Sandhills", "versesCount": 35, "revelationType": "Meccan", "juzStart": 26 },
  { "number": 47, "name": "Muhammad", "arabicName": "محمد", "meaning": "Muhammad", "versesCount": 38, "revelationType": "Medinan", "juzStart": 26 },
  { "number": 48, "name": "Al-Fath", "arabicName": "الفتح", "meaning": "The Victory", "versesCount": 29, "revelationType": "Medinan", "juzStart": 26 },
  { "number": 49, "name": "Al-Hujurat", "arabicName": "الحجرات", "meaning": "The Rooms", "versesCount": 18, "revelationType": "Medinan", "juzStart": 26 },
  { "number": 50, "name": "Qaf", "arabicName": "ق", "meaning": "Qaf", "versesCount": 45, "revelationType": "Meccan", "juzStart": 26 },
  { "number": 51, "name": "Adh-Dhariyat", "arabicName": "الذاريات", "meaning": "The Winnowing Winds", "versesCount": 60, "revelationType": "Meccan", "juzStart": 26 },
  { "number": 52, "name": "At-Tur", "arabicName": "الطور", "meaning": "The Mount", "versesCount": 49, "revelationType": "Meccan", "juzStart": 27 },
  { "number": 53, "name": "An-Najm", "arabicName": "النجم", "meaning": "The Star", "versesCount": 62, "revelationType": "Meccan", "juzStart": 27 },
  { "number": 54, "name": "Al-Qamar", "arabicName": "القمر", "meaning": "The Moon", "versesCount": 55, "revelationType": "Meccan", "juzStart": 27 },
  { "number": 55, "name": "Ar-Rahman", "arabicName": "الرحمن", "meaning": "The Beneficent", "versesCount": 78, "revelationType": "Medinan", "juzStart": 27 },
  { "number": 56, "name": "Al-Waqi'ah", "arabicName": "الواقعة", "meaning": "The Inevitable", "versesCount": 96, "revelationType": "Meccan", "juzStart": 27 },
  { "number": 57, "name": "Al-Hadid", "arabicName": "الحديد", "meaning": "The Iron", "versesCount": 29, "revelationType": "Medinan", "juzStart": 27 },
  { "number": 58, "name": "Al-Mujadila", "arabicName": "المجادلة", "meaning": "The Pleading Woman", "versesCount": 22, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 59, "name": "Al-Hashr", "arabicName": "الحشر", "meaning": "The Exile", "versesCount": 24, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 60, "name": "Al-Mumtahanah", "arabicName": "الممتحنة", "meaning": "The Examined One", "versesCount": 13, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 61, "name": "As-Saff", "arabicName": "الصف", "meaning": "The Ranks", "versesCount": 14, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 62, "name": "Al-Jumu'ah", "arabicName": "الجمعة", "meaning": "Friday", "versesCount": 11, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 63, "name": "Al-Munafiqun", "arabicName": "المنافقون", "meaning": "The Hypocrites", "versesCount": 11, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 64, "name": "At-Taghabun", "arabicName": "التغابن", "meaning": "Mutual Disillusion", "versesCount": 18, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 65, "name": "At-Talaq", "arabicName": "الطلاق", "meaning": "The Divorce", "versesCount": 12, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 66, "name": "At-Tahrim", "arabicName": "التحريم", "meaning": "The Prohibition", "versesCount": 12, "revelationType": "Medinan", "juzStart": 28 },
  { "number": 67, "name": "Al-Mulk", "arabicName": "الملك", "meaning": "The Sovereignty", "versesCount": 30, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 68, "name": "Al-Qalam", "arabicName": "القلم", "meaning": "The Pen", "versesCount": 52, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 69, "name": "Al-Haqqah", "arabicName": "الحاقة", "meaning": "The Inevitable Truth", "versesCount": 52, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 70, "name": "Al-Ma'arij", "arabicName": "المعارج", "meaning": "The Ascending Stairways", "versesCount": 44, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 71, "name": "Nuh", "arabicName": "نوح", "meaning": "Noah", "versesCount": 28, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 72, "name": "Al-Jinn", "arabicName": "الجن", "meaning": "The Jinn", "versesCount": 28, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 73, "name": "Al-Muzzammil", "arabicName": "المزمل", "meaning": "The Enshrouded One", "versesCount": 20, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 74, "name": "Al-Muddaththir", "arabicName": "المدثر", "meaning": "The Cloaked One", "versesCount": 56, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 75, "name": "Al-Qiyamah", "arabicName": "القيامة", "meaning": "The Resurrection", "versesCount": 40, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 76, "name": "Al-Insan", "arabicName": "الإنسان", "meaning": "Man", "versesCount": 31, "revelationType": "Medinan", "juzStart": 29 },
  { "number": 77, "name": "Al-Mursalat", "arabicName": "المرسلات", "meaning": "The Emissaries", "versesCount": 50, "revelationType": "Meccan", "juzStart": 29 },
  { "number": 78, "name": "An-Naba", "arabicName": "النبأ", "meaning": "The Great News", "versesCount": 40, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 79, "name": "An-Nazi'at", "arabicName": "النازعات", "meaning": "Those Who Drag Forth", "versesCount": 46, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 80, "name": "'Abasa", "arabicName": "عبس", "meaning": "He Frowned", "versesCount": 42, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 81, "name": "At-Takwir", "arabicName": "التكوير", "meaning": "The Overthrowing", "versesCount": 29, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 82, "name": "Al-Infitar", "arabicName": "الانفطار", "meaning": "The Cleaving", "versesCount": 19, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 83, "name": "Al-Mutaffifin", "arabicName": "المطففين", "meaning": "Those Who Deal in Fraud", "versesCount": 36, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 84, "name": "Al-Inshiqaq", "arabicName": "الانشقاق", "meaning": "The Splitting Asunder", "versesCount": 25, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 85, "name": "Al-Buruj", "arabicName": "البروج", "meaning": "The Mansions of the Stars", "versesCount": 22, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 86, "name": "At-Tariq", "arabicName": "الطارق", "meaning": "The Nightcomer", "versesCount": 17, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 87, "name": "Al-A'la", "arabicName": "الأعلى", "meaning": "The Most High", "versesCount": 19, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 88, "name": "Al-Ghashiyah", "arabicName": "الغاشية", "meaning": "The Overwhelming Event", "versesCount": 26, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 89, "name": "Al-Fajr", "arabicName": "الفجر", "meaning": "The Dawn", "versesCount": 30, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 90, "name": "Al-Balad", "arabicName": "البلد", "meaning": "The City", "versesCount": 20, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 91, "name": "Ash-Shams", "arabicName": "الشمس", "meaning": "The Sun", "versesCount": 15, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 92, "name": "Al-Layl", "arabicName": "الليل", "meaning": "The Night", "versesCount": 21, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 93, "name": "Ad-Duha", "arabicName": "الضحى", "meaning": "The Morning Hours", "versesCount": 11, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 94, "name": "Ash-Sharh", "arabicName": "الشرح", "meaning": "The Relief", "versesCount": 8, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 95, "name": "At-Tin", "arabicName": "التين", "meaning": "The Fig", "versesCount": 8, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 96, "name": "Al-'Alaq", "arabicName": "العلق", "meaning": "The Clot", "versesCount": 19, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 97, "name": "Al-Qadr", "arabicName": "القدر", "meaning": "The Power", "versesCount": 5, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 98, "name": "Al-Bayyinah", "arabicName": "البينة", "meaning": "The Clear Proof", "versesCount": 8, "revelationType": "Medinan", "juzStart": 30 },
  { "number": 99, "name": "Az-Zalzalah", "arabicName": "الزلزلة", "meaning": "The Earthquake", "versesCount": 8, "revelationType": "Medinan", "juzStart": 30 },
  { "number": 100, "name": "Al-'Adiyat", "arabicName": "العاديات", "meaning": "The Courser", "versesCount": 11, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 101, "name": "Al-Qari'ah", "arabicName": "القارعة", "meaning": "The Calamity", "versesCount": 11, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 102, "name": "At-Takathur", "arabicName": "التكاثر", "meaning": "The Rivalry in World Increase", "versesCount": 8, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 103, "name": "Al-'Asr", "arabicName": "العصر", "meaning": "The Declining Day", "versesCount": 3, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 104, "name": "Al-Humazah", "arabicName": "الهمزة", "meaning": "The Traducer", "versesCount": 9, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 105, "name": "Al-Fil", "arabicName": "الفيل", "meaning": "The Elephant", "versesCount": 5, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 106, "name": "Quraysh", "arabicName": "قريش", "meaning": "Quraysh", "versesCount": 4, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 107, "name": "Al-Ma'un", "arabicName": "الماعون", "meaning": "The Small Kindness", "versesCount": 7, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 108, "name": "Al-Kawthar", "arabicName": "الکوثر", "meaning": "The Abundance", "versesCount": 3, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 109, "name": "Al-Kafirun", "arabicName": "الكافرون", "meaning": "The Disbelievers", "versesCount": 6, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 110, "name": "An-Nasr", "arabicName": "النصر", "meaning": "The Divine Support", "versesCount": 3, "revelationType": "Medinan", "juzStart": 30 },
  { "number": 111, "name": "Al-Masad", "arabicName": "المسد", "meaning": "The Palm Fiber", "versesCount": 5, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 112, "name": "Al-Ikhlas", "arabicName": "الإخلاص", "meaning": "The Sincerity", "versesCount": 4, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 113, "name": "Al-Falaq", "arabicName": "الفلق", "meaning": "The Daybreak", "versesCount": 5, "revelationType": "Meccan", "juzStart": 30 },
  { "number": 114, "name": "An-Nas", "arabicName": "الناس", "meaning": "Mankind", "versesCount": 6, "revelationType": "Meccan", "juzStart": 30 }
];

async function match() {
  const banners = JSON.parse(fs.readFileSync('scratch/exact_banner_list.json', 'utf8'));
  console.log('Total banner records:', banners.length);
  
  // Group banners by page
  const pageBanners = {};
  for (const b of banners) {
    if (!pageBanners[b.page]) pageBanners[b.page] = [];
    pageBanners[b.page].push(b);
  }

  const pagesWithBanners = Object.keys(pageBanners).map(Number).sort((a,b) => a - b);
  console.log('Unique pages with banners:', pagesWithBanners.length);
  console.log(pagesWithBanners);
}

match().catch(console.error);
